### PR TITLE
Add Linux installation instructions and reorganize content

### PR DESCRIPTION
**Pull request by elmhadji**
- Added a new Linux section with installation instructions for Ubuntu/Debian, Fedora, and Arch Linux
- Included command to run SKlauncher JAR file on Linux
- Reorganized content for better logical flow
- Minor formatting improvements throughout the document

### CODE REVIEW

**Comment by skmedix** [comment]
Let's bump it to java 21 lts, and it LGTM!

**Comment by SoyRA** [comment]
> Didn't understand you can you explain it for me , if you don't mind ?

@elmhadji The latest Java LTS is 21, so instead of recommending Java 17 recommend Java 21. a,a
PS: LGTM = Looks good to me

**Comment by elmhadji** [comment]
> 17

Thanks for the explanation 😁

**Comment by elmhadji** [comment]
@skmedix I've updated the pull request based on your feedback. I've made update the java version from 17 to 21 

Please let me know if there's anything else that needs to be addressed . Thank you for your review 😁****

**Pull request merged**
